version: "3"
services:
  test-app:
    container_name: test-app
    build:
      context: ./
      dockerfile: ./packages/app/docker/Dockerfile.dev
    volumes:
      - ./:/home/app
    ports:
      - 14005:3000

  nginx:
    container_name: test-nginx
    image: newfront/nginx-dev:0.1.0
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 14000:8088
    command:
      [
        "dockerize",
        "-timeout",
        "90s",
        "-wait",
        "tcp://test-app:3000",
        "nginx",
        "-g",
        "daemon off;",
      ]
    depends_on:
      - test-app
